src/Entity/PostForum.php
<?php

namespace App\Entity;

use App\Repository\PostForumRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PostForumRepository::class)]
class PostForum
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'postForums')]
    #[ORM\JoinColumn(nullable: false)]
    private ?CategoryForum $categorie = null;

    #[ORM\Column(length: 150)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 15,
        max: 150,
        minMessage: 'Post Content must be atleast {{ limit }} characters long',
        maxMessage: 'Post Content cant be longer than {{ limit }} characters',
    )]
    private ?string $contenu = null;

    #[ORM\Column(length: 80)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 3,
        max: 30,
        minMessage: 'Post Title must be atleast {{ limit }} characters long',
        maxMessage: 'Post Title cant be longer than {{ limit }} characters',
    )]
    private ?string $titre = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column]
    private ?int $user_id = null;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: CommentairePost::class, orphanRemoval: true)]
    private Collection $commentairePosts;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: PostLike::class, orphanRemoval: true)]
    private Collection $postLikes;

    public function __construct()
    {
        $this->commentairePosts = new ArrayCollection();
        $this->postLikes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategorie(): ?CategoryForum
    {
        return $this->categorie;
    }

    public function setCategorie(?CategoryForum $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * @return Collection<int, CommentairePost>
     */
    public function getCommentairePosts(): Collection
    {
        return $this->commentairePosts;
    }

    public function addCommentairePost(CommentairePost $commentairePost): self
    {
        if (!$this->commentairePosts->contains($commentairePost)) {
            $this->commentairePosts->add($commentairePost);
            $commentairePost->setPost($this);
        }

        return $this;
    }

    public function removeCommentairePost(CommentairePost $commentairePost): self
    {
        if ($this->commentairePosts->removeElement($commentairePost)) {
            // set the owning side to null (unless already changed)
            if ($commentairePost->getPost() === $this) {
                $commentairePost->setPost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, PostLike>
     */
    public function getPostLikes(): Collection
    {
        return $this->postLikes;
    }

    public function addPostLike(PostLike $postLike): self
    {
        if (!$this->postLikes->contains($postLike)) {
            $this->postLikes->add($postLike);
            $postLike->setPost($this);
        }

        return $this;
    }

    public function removePostLike(PostLike $postLike): self
    {
        if ($this->postLikes->removeElement($postLike)) {
            // set the owning side to null (unless already changed)
            if ($postLike->getPost() === $this) {
                $postLike->setPost(null);
            }
        }

        return $this;
    }
    public function __toString(){
        return (string)$this->titre;
    }
}

src/Form/PostForumType.php
<?php

namespace App\Form;

use App\Entity\CategoryForum;
use App\Entity\PostForum;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class PostForumType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            
            ->add('titre',TextType::class, array('label' => 'Titre de post','label_attr'=>['class' => 'col-md-4 col-lg-3 col-form-label'],'attr' => array( 'placeholder' => 'Titre de poste','class' => 'form-control')))
            ->add('contenu',TextareaType::class, array('label' => 'Contenu du Post','label_attr'=>['class' => 'col-md-4 col-lg-3 col-form-label'],'attr' => array( 'placeholder' => 'Contenu du post','class' => 'form-control')))
            ->add('categorie',null, array('label' => 'Nom du Categorie','label_attr'=>['class' => 'col-md-4 col-lg-3 col-form-label'],'attr' => array( 'class' => 'form-control','mapped' => true)))

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PostForum::class,
        ]);
    }
}

src/Controller/PostForumController.php
<?php

namespace App\Controller;

use App\Entity\PostForum;
use App\Form\PostForumType;
use App\Repository\PostForumRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/post/forum')]
class PostForumController extends AbstractController
{
    #[Route('/', name: 'app_post_forum_index', methods: ['GET'])]
    public function index(PostForumRepository $postForumRepository): Response
    {
        return $this->render('post_forum/index.html.twig', [
            'post_forums' => $postForumRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_post_forum_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PostForumRepository $postForumRepository): Response
    {
        $postForum = new PostForum();
        $form = $this->createForm(PostForumType::class, $postForum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $postForum->setCreatedAt(new \DateTime());
            $postForum->setUserId(1);
            $postForumRepository->save($postForum, true);

            return $this->redirectToRoute('app_post_forum_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('post_forum/new.html.twig', [
            'post_forum' => $postForum,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_post_forum_show', methods: ['GET'])]
    public function show(PostForum $postForum): Response
    {
        return $this->render('post_forum/show.html.twig', [
            'post_forum' => $postForum,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_post_forum_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, PostForum $postForum, PostForumRepository $postForumRepository): Response
    {
        $form = $this->createForm(PostForumType::class, $postForum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $postForumRepository->save($postForum, true);

            return $this->redirectToRoute('app_post_forum_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('post_forum/edit.html.twig', [
            'post_forum' => $postForum,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_post_forum_delete', methods: ['POST'])]
    public function delete(Request $request, PostForum $postForum, PostForumRepository $postForumRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$postForum->getId(), $request->request->get('_token'))) {
            $postForumRepository->remove($postForum, true);
        }

        return $this->redirectToRoute('app_post_forum_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/post_forum/_delete_form.html.twig
<form method="post" action="{{ path('app_post_forum_delete', {'id': post_forum.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post_forum.id) }}">
    <div class="row mb-3">
        <button class="btn btn-danger">Delete</button>
    </div>
</form>

templates/post_forum/_form.html.twig
{{ form_start(form, {'attr': {'novalidate':'novalidate'}}) }}
    {{ form_widget(form) }}
<br>
<div class="row mb-3">
    <button class="btn btn-primary" >{{ button_label|default('Save') }}</button>
</div>
{{ form_end(form) }}

templates/post_forum/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit PostForum{% endblock %}

{% block body %}
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Gestion des Posts du forum</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item">Gestion Forum</li>
                <li class="breadcrumb-item active">Posts</li>
                <li class="breadcrumb-item active">Edit</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    <div  style="display:flex;justify-content: center;align-items: center;margin:1rem 0;"> <button class="btn btn-primary"> <a style="color:white;text-decoration: none" href="{{ path('app_post_forum_new') }}">Create new</a></button>
    </div>
    <section class="section">
        <div class="row">
            <div >
                <div class="card">
                    <div class="card-body">
                        <div class="row mb-3">

    {{ include('post_forum/_form.html.twig', {'button_label': 'Update'}) }}
                        </div>
                        <div class="row mb-3">

                {{ include('post_forum/_delete_form.html.twig') }}
                        </div>
    <div class="row mb-3">
        <a  class="btn btn-secondary" style="color:white;text-decoration: none"href="{{ path('app_post_forum_index') }}">back to list</a>
    </div>
                    </div>
                </div>

            </div>
        </div>
    </section>

</main><!-- End #main -->

{% endblock %}

templates/post_forum/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Posts List{% endblock %}

{% block body %}

    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Gestion des Posts du forum</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item">Gestion Forum</li>
                    <li class="breadcrumb-item active">Posts</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->
        <div  style="display:flex;justify-content: center;align-items: center;margin:1rem 0;"> <button class="btn btn-primary"> <a style="color:white;text-decoration: none" href="{{ path('app_post_forum_new') }}">Create new</a></button>
        </div>
        <section class="section">
            <div class="row">
                <div >
                    <div class="card">
                        <div class="card-body">

                            <table class="table table-info" style="margin:2rem 0 2rem 0">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Contenu</th>
                                    <th>Titre</th>
                                    <th>Created_at</th>
                                    <th>User_id</th>
                                    <th>actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for post_forum in post_forums %}
                                    <tr>
                                        <td>{{ post_forum.id }}</td>
                                        <td>{{ post_forum.contenu }}</td>
                                        <td>{{ post_forum.titre }}</td>
                                        <td>{{ post_forum.createdAt ? post_forum.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                                        <td>{{ post_forum.userId }}</td>
                                        <td>
                                            <a class="btn btn-primary" href="{{ path('app_post_forum_show', {'id': post_forum.id}) }}">Show</a>
                                            <a class="btn btn-danger" href="{{ path('app_post_forum_edit', {'id': post_forum.id}) }}">Edit</a>
                                        </td>
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td colspan="6">no records found</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main><!-- End #main -->


{% endblock body %}

templates/post_forum/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Post{% endblock %}
{% block body %}

    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Gestion des Posts du forum</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item">Gestion Forum</li>
                    <li class="breadcrumb-item ">Post</li>
                    <li class="breadcrumb-item active">New</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div>
                    <div class="card">
                        <div class="card-body">

                            {{ include('post_forum/_form.html.twig') }}
                            <div class="row mb-3">
                                <a class="btn btn-secondary" style="color:white;text-decoration: none"
                                   href="{{ path('app_post_forum_index') }}">back to list</a>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main><!-- End #main -->


{% endblock body %}

templates/post_forum/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}PostForum{% endblock %}

{% block body %}
    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Gestion des Posts du forum</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item">Gestion Forum</li>
                    <li class="breadcrumb-item active">Post </li>
                    <li class="breadcrumb-item active">Details </li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div >
                    <div class="card">
                        <div class="card-body">
                            <table class="table table-info" style="margin:2rem 0 2rem 0">
                                <tbody>
                                <tr>
                                    <th>Id</th>
                                    <td>{{ post_forum.id }}</td>
                                </tr>
                                <tr>
                                    <th>Contenu</th>
                                    <td>{{ post_forum.contenu }}</td>
                                </tr>
                                <tr>
                                    <th>Titre</th>
                                    <td>{{ post_forum.titre }}</td>
                                </tr>
                                <tr>
                                    <th>Created_at</th>
                                    <td>{{ post_forum.createdAt ? post_forum.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                                </tr>
                                <tr>
                                    <th>User_id</th>
                                    <td>{{ post_forum.userId }}</td>
                                </tr>
                                </tbody>
                            </table>
                                <div class="row mb-3">
                                    <a class="btn btn-primary" href="{{ path('app_post_forum_edit', {'id': post_forum.id}) }}">Edit</a>
                                </div>


                            {{ include('post_forum/_delete_form.html.twig') }}

                                <div class="row mb-3">
                                    <a class="btn btn-secondary"href="{{ path('app_post_forum_index') }}">Back to list</a>
                                </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main><!-- End #main -->



{% endblock %}